# Generated by Django 5.2.4 on 2025-07-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='Pictures',
        ),
    ]
