# Generated by Django 5.2.4 on 2025-07-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sitevisit',
            table='site_visits',
        ),
    ]
